#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=72,2,4,31,41,43,46,54,56&i=1,2,3,4,15,16,17,28,29,30&v=4,5,-1,2,27,26,25,35,34,32 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ILI9488
#define BRIGHTNESS_PIN			2
#define PLAYER_FORCE_MONO			true
#define ENC_BTNR			35
#define ENC_BTNL			34
#define ENC_BTNB			32

#define L10N_LANGUAGE     	RU 

#endif